---
- hosts: prometheus
  roles:
    - cloudalchemy.prometheus
  vars:
    prometheus_targets:
      node:
        - targets:
            - 'localhost:9100'
            - 'demo.cloudalchemy.org:9100'
            - 'ala.kot:9110'
          labels:
            env: demosite

- hosts: localhost
  tasks:
    - name: Create security group
      ec2_group:
        name: prometheus-port-sg
        description: SG for app prometheus
        vpc_id: vpc-052e1bd54be74daf9
        region: us-east-1
        aws_access_key: '{{ec2_access_key}}'
        aws_secret_key: '{{ec2_secret_key}}'
        rules:
          - proto: tcp
            ports:
              - 9090
            cidr_ip: 0.0.0.0/0
            rule_desc: allow all on prometheus port
      register: result_sec_group
